[package]
name = "monitrous"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "0.9.0" 
image = "0.24.5"
xml-rs = "0.8.4"
